type Mutation {
  """
  新しいユーザーを作成する
  """
  createUser(username: String!): User

  """
  新しいポストを作成する
  """
  createPost(userUuid: String!, title: String, content: String): Post

  """
  新しいメディアを作成する
  """
  createMedia(
    userUuid: String!
    file: Upload!
    filename: String!
    contentType: String!
    width: Int!
    height: Int!
    ratio: Float!
  ): Post

  """
  新しいタグを作成する
  """
  createTag(name: String!, userUuid: String!): Tag

  """
  新しいコメントを作成する
  """
  createComment(
    userUuid: String!
    mediaUuid: String!
    content: String!
  ): Comment

  """
  メディアにタグを追加する
  """
  addTagToMedia(
    mediaUuid: String!
    tagUuid: String!
    userUuid: String!
  ): MediaTag

  """
  タグの評価を追加する
  """
  addEvaluationToTag(
    tagUuid: String!
    evaluationUuid: String!
    userUuid: String!
  ): TagEvaluation

  """
  メディアの評価を追加する
  """
  addEvaluationToMedia(
    mediaUuid: String!
    evaluationUuid: String!
    userUuid: String!
  ): MediaEvaluation

  """
  メディアに対してアクションを追加する
  """
  addActionToMedia(
    mediaUuid: String!
    actionType: String!
    userUuid: String!
  ): MediaAction

  """
  コメントに対してアクションを追加する
  """
  addActionToComment(
    commentUuid: String!
    actionType: String!
    userUuid: String!
  ): CommentAction

  """
  メディアをお気に入りに追加する
  """
  addMediaToFavorites(mediaUuid: String!, userUuid: String!): Favorite

  """
  メディアからお気に入りを削除する
  """
  removeMediaFromFavorites(favoriteUuid: String!): Favorite

  """
  メディアのコメントを追加する
  """
  addCommentToMedia(
    mediaUuid: String!
    userUuid: String!
    content: String!
  ): MediaComment

  """
  コメントのコメントを追加する
  """
  addCommentToComment(
    commentUuid: String!
    userUuid: String!
    content: String!
  ): Comment

  signIn(signInIdentifier: String!, password: String!): ResAuthenticationResult

  signUp(username: String!, email: String!, password: String!): User

  resendConfirmationCode(uuid: String!): Boolean

  confirmSignUp(uuid: String!, code: String!): Boolean

  changeEmail(accessToken: String!, newEmail: String): Boolean

  changeUserDetail(accessToken: String!, newEmail: String): Boolean

  verifyEmail(
    accessToken: String!
    newEmail: String!
    beforeEmail: String!
    code: String!
  ): Boolean

  signOut(accessToken: String!): Boolean

  resetPassword(email: String!): Boolean

  confirmResetPassword(
    email: String!
    code: String!
    newPassword: String!
  ): Boolean

  changePassword(
    accessToken: String!
    oldPassword: String!
    newPassword: String!
  ): Boolean
}
